version: '3.5'

services:

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - nginx-example

networks:
  nginx-example:
    name: nginx-example
    driver: bridge
