version: '3'

services:

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - nginx-example

networks:
  nginx-example:
    external: true
    driver: bridge
