version: '3'

services:
  site1:
    image: php:8.2-fpm-alpine
    container_name: site1
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - nginx-example


networks:
  nginx-example:
    external: true
    driver: bridge
