version: '3.5'

services:
  site2:
    image: php:8.2-fpm-alpine
    container_name: site2
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - nginx-example


networks:
  nginx-example:
    name: nginx-example
    external: true
    driver: bridge
